id: IC13DBAD0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T12:54:35+00:00'
last_modified: '2022-06-07T15:05:01.944275+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18517
  title: བོད་ཀྱི་གསོ་རིག་དམའ་རིམ་ཆུ་ཚད་ཀྱི་སྤྱོད་བདེ་སློབ་དེབ། ནད་ཐོག་ལག་ལེན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    AB69:
      image_group_id: I8LS18519
      title: ''
      total_pages: 364
      order: 1
      base_file: AB69.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
