id: P001768
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS18517
  title: བོད་ཀྱི་གསོ་རིག་དམའ་རིམ་ཆུ་ཚད་ཀྱི་སྤྱོད་བདེ་སློབ་དེབ། ནད་ཐོག་ལག་ལེན།
  author: ''
  volumes:
    801477b00b4a4adfaade23359ba69bb9:
      image_group_id: I8LS18519
      title: ''
      volume_number: 1
      total_pages: 364
      base_file: v001.txt
